apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-worker-app
spec:
  selector:
    matchLabels:
      app: worker-app
  replicas: 3
  template:
    metadata:
      name: pod-worker-app
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
