apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 3
  template:
    metadata:
      name: pod-database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: posgres
          ports:
            - containerPort: 5432
              hostPort: 5432
