apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      name: pod-database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust

