apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc3
spec:
  replicas: 3
  selector:
    app: myapp-label
  template:
    metadata:
      name: myapp
      labels:
        app: myapp-label
    spec:
      containers:
        - name: nginx-container-1
          image: nginx